[package]
name = "bookmark-language"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.153", features = ["derive", "rc"] }
tap = "1.0.1"
thiserror = "1.0.39"
